-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         8.4.3 - MySQL Community Server - GPL
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para escuela
CREATE DATABASE IF NOT EXISTS `escuela` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `escuela`;

-- Volcando estructura para tabla escuela.materias
CREATE TABLE IF NOT EXISTS `materias` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(70) NOT NULL,
  `abreviatura` varchar(15) NOT NULL,
  `estado` varchar(1) NOT NULL DEFAULT 'H',
  `resumen` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=utf8mb3;

-- Volcando datos para la tabla escuela.materias: ~129 rows (aproximadamente)
REPLACE INTO `materias` (`id`, `nombre`, `abreviatura`, `estado`, `resumen`) VALUES
	(1, 'ANALISIS MATEMATICO', 'ANMAT', 'H', 'ANAL. MAT.'),
	(2, 'EDUCACIÃ“N ARTÃSTICA', 'ART', 'H', 'ED. ARTISTICA'),
	(3, 'ARTE', 'ARTE', 'H', 'ARTE'),
	(4, 'BASE DE DATOS', 'BADA', 'H', 'BASE DE DATOS'),
	(5, 'BIOLOGÃA', 'BIO', 'H', 'BIOLOGIA'),
	(6, 'CONSTRUCCIÃ“N CIUDADANA', 'CDC', 'H', 'CONST. CIUD.'),
	(7, 'COMERCIALIZACION DE EMPRESAS TURISTICAS Y HOTELERA', 'CETH', 'H', 'COM. E. T. H.'),
	(8, 'CONOCIMIENTO DE LOS MATERIALES', 'COMA', 'H', 'CON. DE MAT.'),
	(9, 'DIRECCION DE EMPRESAS TURISTICAS Y HOTELERAS', 'DEMTH', 'H', 'DIR. E. T. Y H.'),
	(10, 'DIRECCION DE LA EJECUCION DE INSTALACIONES', 'DEREI', 'H', 'DIR. EJ. INST.'),
	(11, 'DERECHO DE TRABAJO', 'DETRA', 'H', 'DER. TRAB.'),
	(12, 'SISTEMA DIGITALES', 'DIGI5', 'H', 'SIST. DIG.'),
	(13, 'SISTEMA DIGITALES', 'DIGI6', 'H', 'SIST. DIG.'),
	(14, 'DIRECCION DE OBRA', 'DIROB', 'H', 'DIR. DE OBRA'),
	(15, 'ECONOMIA', 'ECON', 'H', 'ECONOMIA'),
	(16, 'EDUCACIÃ“N FÃSICA', 'EFI', 'H', 'ED. FISICA'),
	(17, 'EDUCACION FISICA', 'EFIS', 'H', 'ED. FISICA'),
	(18, 'EMPRESAS HOTELERAS', 'EMPHO', 'H', 'EMP. HOT.'),
	(19, 'EJERCICIO PROFESIONAL DE LA CONSTRUCCION', 'EPCON', 'H', 'EJ. PR. CONS.'),
	(20, 'ESTRUCTURAS', 'EST6', 'H', 'ESTRUCTURAS'),
	(21, 'ESTRUCTURAS', 'EST7', 'H', 'ESTRUCTURAS'),
	(22, 'ESPACIOS TURISTICOS DE LA ARGENTINA', 'ESTA', 'H', 'ESP. TUR. ARG.'),
	(23, 'EVALUACION DE PROYECTOS', 'EVPRO', 'H', 'EV. DE PROY.'),
	(24, 'FILOSOFIA', 'FILO', 'H', 'FILOSOFIA'),
	(25, 'FISICA', 'FIS', 'H', 'FISICA'),
	(26, 'DESARROLLO DE APLICACIONES WEB DINAMICAS', 'FTDD6', 'H', 'DES. A. W. D.'),
	(27, 'DESARROLLO DE APLICACIONES WEB ESTATICAS', 'FTDE6', 'H', 'DES. A. W. E.'),
	(28, 'DIBUJO TECNOLOGICO', 'FTDT4', 'H', 'DIB. TECN.'),
	(29, 'DOCUMENTACION TECNICA', 'FTDT5', 'H', 'DOC. TEC. '),
	(30, 'INTERPRETACION DE ANTEPROYECTOS', 'FTIA4', 'H', 'INT. ANTEP.'),
	(31, 'INTRODUCCION AL TURISMO Y OFERTA TURISTICA', 'FTIT4', 'H', 'INT. T. Y O. T.'),
	(32, 'LABORATORIO DE APLICACIONES', 'FTLA4', 'H', 'LAB. DE AP.'),
	(33, 'LABORATORIO DE DISEÃ‘O DE DATOS', 'FTLD5', 'H', 'LAB. DIS. BD.'),
	(34, 'LABORATORIO DE HARDWARE', 'FTLH4', 'H', 'LAB. HARD.'),
	(35, 'LABORATORIO DE PROGRAMACION', 'FTLP4', 'H', 'LAB. PROG.'),
	(36, 'LABORATORIO DE PROGRAMACION', 'FTLP5', 'H', 'LAB. PROG.'),
	(37, 'LABORATORIO DE PROGRAMACION III', 'FTLP6', 'H', 'LAB. PROG. III'),
	(38, 'LABORATORIO DE REDES INFORMATICAS', 'FTLR5', 'H', 'LAB. RED. INF. '),
	(39, 'LABORATORIO DE SISTEMAS OPERATIVOS', 'FTLS4', 'H', 'LAB. SIST. OP.'),
	(40, 'LABORATORIO DE DISEÃ‘O WEB', 'FTLW5', 'H', 'LAB. DIS. WEB'),
	(41, 'MATERIALES DE OBRA', 'FTMO5', 'H', 'MAT. DE OBRA'),
	(42, 'LABORATORIO DE PROCESOS INDUSTRIALES', 'FTPI6', 'H', 'LAB. PROC. IND. '),
	(43, 'PLANIFICACION DE OBRA', 'FTPO4', 'H', 'PLAN. OBRA'),
	(44, 'PROYECTO', 'FTPR4', 'H', 'PROYECTO'),
	(45, 'PROYECTO', 'FTPR5', 'H', 'PROYECTO'),
	(46, 'PROYECTO', 'FTPR6', 'H', 'PROYECTO'),
	(47, 'PROGRAMACION DE CIRCUITOS TURISTICOS', 'FTPT5', 'H', 'PRO. C. T.'),
	(48, 'INVESTIGACION DE MERCADOS', 'FTPT6', 'H', 'INV. MERCADOS'),
	(49, 'RECURSOS LINGUISTICOS', 'FTRL5', 'H', 'REC. LING. '),
	(50, 'RECURSOS LINGUISTICOS', 'FTRL6', 'H', 'REC. LING. '),
	(51, 'RECURSOS LINGUISTICOS', 'FTRL7', 'H', 'REC. LING. '),
	(52, 'SISTEMAS CONSTRUCTIVOS', 'FTSC4', 'H', 'SIST. CONST.'),
	(53, 'SISTEMAS CONSTRUCTIVOS', 'FTSC5', 'H', 'SIST. CONST.'),
	(54, 'SISTEMAS CONSTRUCTIVOS', 'FTSC6', 'H', 'SIST. CONST.'),
	(55, 'SISTEMAS DE INFORMACION CONTABLE', 'FTSI4', 'H', 'SIST. INF. CONT.'),
	(56, 'SISTEMA DE INFORMACION CONTABLE', 'FTSI5', 'H', 'SIST. INF. CONT.'),
	(57, 'TECNOLOGIA DE LA INFORMACION TURISTICA', 'FTTT4', 'H', 'TEC. INF. TUR. '),
	(58, 'TECNOLOGIA DE LA INFORMACION TURISTICA', 'FTTT5', 'H', 'TEC. INF. TUR. '),
	(59, 'PROGRAMACION DE CIRCUITOS TURISTICOS', 'FTTT6', 'H', 'PROG. CIR. TUR.'),
	(60, 'SERVICIOS TURISTICOS', 'FTTV4', 'H', 'SERV. TUR. '),
	(61, 'GEOGRAFÃA', 'GEO', 'H', 'GEOGRAFIA'),
	(62, 'GEOGRAFIA', 'GEOS', 'H', 'GEOGRAFIA'),
	(63, 'GEOGRAFIA', 'GEOS5', 'H', 'GEOGRAFIA'),
	(64, 'HISTORIA', 'HIS', 'H', 'HISTORIA'),
	(65, 'HISTORIA', 'HIS5', 'H', 'HISTORIA'),
	(66, 'INGLES', 'ING', 'H', 'INGLES'),
	(67, 'INGLES', 'INGS', 'H', 'INGLES'),
	(68, 'INSTALACIONES DE ACONDICIONAMIENTO DE AIRE', 'INSAA', 'H', 'INST. A.A.'),
	(69, 'INSTALACIONES ELECTRICAS', 'INSE', 'H', 'INST. ELEC. '),
	(70, 'INSTALACIONES SANITARIAS Y DE GAS', 'INSG', 'H', 'INST. S. Y G.'),
	(71, 'INTRODUCCION AL PORTUGUES', 'INTP', 'H', 'INT. PORT.'),
	(72, 'LITERATURA', 'LITS', 'H', 'LITERATURA'),
	(73, 'MATEMÃTICA', 'MAT', 'H', 'MATEMATICA'),
	(75, 'MATEMATICA APLICADA', 'MATAP', 'H', 'MAT. APL.'),
	(76, 'MATEMATICA DISCRETA', 'MATDI', 'H', 'MAT. DISC. '),
	(77, 'MATEMATICA-CICLO SUPERIOR', 'MATES', 'H', 'MAT. CICLO SUP.'),
	(78, 'MODELOS Y SISTEMAS', 'MOSI7', 'H', 'MOD. Y SIST. '),
	(79, 'MODELOS Y SISTEMAS', 'MOSIS', 'H', 'MOD. Y SIST. '),
	(80, 'CIENCIAS NATURALES', 'NAT', 'H', 'CS. NAT. '),
	(81, 'ORGANIZACION Y METODOS', 'ORMET', 'H', 'ORG. Y MET.'),
	(82, 'PATRIMONIO TURISTICO NACIONAL E INTERNACIONAL', 'PATNI', 'H', 'PAT. T. N. I. '),
	(83, 'PROYECTO, DISEÃ‘O E IMPLEMENTACION DE SISTEMAS COMPUTACIONALES', 'PDISC', 'H', 'PROY. D. I. S. C.'),
	(84, 'PROYECTO DE DESARROLLO SOFTWARE PARA PLATAFORMAS MOVILES', 'PDSPM', 'H', 'PROY. D. S. P. M. '),
	(85, 'PROYECTO DE IMPLEMENTACION DE SITIOS WEB DINAMICOS', 'PISWD', 'H', 'PROY. I. S. W. D. '),
	(86, 'PRÃCTICAS DE LENGUAJE', 'PLG', 'H', 'PRAC. LENG. '),
	(87, 'EMPRENDIMIENTOS PRODUCTIVOS Y DESARROLLO LOCAL', 'PPDLO', 'H', 'EMP. P. D. L. '),
	(88, 'PRACTICAS PROFESIONALIZANTES DEL SECTOR CONSTRUCTIVO', 'PPSCE', 'H', 'PRAC. P. C. '),
	(89, 'PRACTICAS PROFESIONALIZANTES DEL SECTOR INFORMATICO', 'PPSIN', 'H', 'PRAC. P. I. '),
	(90, 'PRACTICAS PROFESIONALIZANTES DEL SECTOR SERVICIOS', 'PPSST', 'H', 'PRAC. P. T.'),
	(91, 'PROYECTO FINAL', 'PROFI', 'H', 'PROY. FINAL'),
	(92, 'PROYECTO DE INSTALACIONES', 'PROIN', 'H', 'PROY. INST. '),
	(93, 'PSICOLOGIA', 'PSIC', 'H', 'PSICOLOGIA'),
	(94, 'POLITICA Y CIUDADANIA', 'PYCS', 'H', 'POL. Y CIUD. '),
	(95, 'QUIMICA', 'QUI', 'H', 'QUIMICA'),
	(96, 'RESISTENCIA Y ENSAYOS DE MATERIALES', 'REMAT', 'H', 'RES. Y E. M. '),
	(97, 'RELACIONES PUBLICAS, PROTOCOLO Y CEREMONIAL', 'REPC', 'H', 'REL. P. P. C. '),
	(98, 'SALUD Y ADOLESCENCIA', 'SADS', 'H', 'SAL. Y AD. '),
	(99, 'SEGURIDAD INFORMATICA', 'SEINF', 'H', 'SEG. INF. '),
	(100, 'SISTEMA DE GESTION Y AUTOGESTION', 'SGEAU', 'H', 'SIST. G. Y A. '),
	(101, 'CIENCIAS SOCIALES', 'SOC', 'H', 'CS. SOCIALES'),
	(102, 'TECNOLOGIAS ELECTRONICAS', 'TECEL', 'H', 'TEC. ELEC.'),
	(103, 'LENGUAJES TECNOLÃ“GICOS', 'TLT1', 'H', 'LENG. TECN. '),
	(104, 'LENGUAJES TECNOLÃ“GICOS', 'TLT2', 'H', 'LENG. TECN.'),
	(105, 'LENGUAJES TECNOLÃ“GICOS', 'TLT3', 'H', 'LENG. TECN.'),
	(106, 'PROCEDIMIENTOS TECNICOS', 'TPT1', 'H', 'PROC. TECN. '),
	(107, 'PROCEDIMIENTOS TECNICOS', 'TPT2', 'H', 'PROC. TECN. '),
	(108, 'PROCEDIMIENTOS TECNICOS', 'TPT3', 'H', 'PROC. TECN. '),
	(109, 'SISTEMAS TECNOLÃ“GICOS', 'TST1', 'H', 'SIST. TECN. '),
	(110, 'SISTEMAS TECNOLÃ“GICOS', 'TST2', 'H', 'SIST. TECN. '),
	(111, 'SISTEMAS TECNOLÃ“GICOS', 'TST3', 'H', 'SIST. TECN. '),
	(112, 'FISICO-QUIMICA', 'FIQUI', 'H', 'FIS-QUIM.'),
	(113, 'BASE DE DATOS', 'BADA5', 'H', 'BASE DE DATOS'),
	(114, 'SISTEMAS DIGITALES', 'SIDI5', 'H', 'SIST. DIG.'),
	(115, 'Preceptro', 'PR', 'D', ''),
	(116, 'Preceptor', 'PR', 'H', ''),
	(117, 'CIENCIAS SOCIALES (1A)', 'SOC', 'H', 'CS. SOCIALES'),
	(118, 'CIENCIAS SOCIALES (1B)', 'SOC', 'H', 'CS. SOCIALES'),
	(119, 'CIENCIAS SOCIALES (1C)', 'SOC', 'H', 'CS. SOCIALES'),
	(120, 'CIENCIAS SOCIALES (1D)', 'SOC', 'H', 'CS. SOCIALES'),
	(121, 'CIENCIAS SOCIALES (1E)', 'SOC', 'H', 'CS. SOCIALES'),
	(122, 'CIENCIAS SOCIALES (1F)', 'SOC', 'H', 'CS. SOCIALES'),
	(123, 'CIENCIAS SOCIALES (1G)', 'SOC', 'H', 'CS. SOCIALES'),
	(124, 'CIENCIAS NATURALES (1A)', 'NAT', 'H', 'CS. NAT.'),
	(125, 'CIENCIAS NATURALES (1B)', 'NAT', 'H', 'CS. NAT.'),
	(126, 'CIENCIAS NATURALES (1C)', 'NAT', 'H', 'CS. NAT.'),
	(127, 'CIENCIAS NATURALES (1D)', 'NAT', 'H', 'CS. NAT.'),
	(128, 'CIENCIAS NATURALES (1E)', 'NAT', 'H', 'CS. NAT.'),
	(129, 'CIENCIAS NATURALES (1F)', 'NAT', 'H', 'CS. NAT.'),
	(130, 'CIENCIAS NATURALES (1G)', 'NAT', 'H', 'CS. NAT.');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
